### ISSUE TITLE
github.com/gonuts/config

### ISSUE THREAD

**Issue by h4ck3rm1k3** [lhcb-org/lbpkr#37]
this repo is awol
- "github.com/gonuts/config"

**Comment by sbinet** [comment]
oops. I'll put it back (overenthusiastic spring cleaning)

**Comment by sbinet** [comment]
done.

**Comment by h4ck3rm1k3** [comment]
what commit please, cannot find it

**Comment by sbinet** [comment]
it's not in `lbpkr` per se.
it's on the `github.com/gonuts/config` repo. I mistakenly deleted it.
now it's live again:
 https://github.com/gonuts/config

so you should be able to go to `github.com/lhcb-org/lbpkr` under your `$GOPATH/src` directory and do:
```sh
$ go get -v .
```

hth,
-s
